name: tester

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v2
      - name: Tester name
        run: echo "Tested by Bogdan"
      - name: Get working directory
        run: pwd
      - name: Compile
        run: gcc -o sum sum.c
      - name: Test cases
        run: |
            if [ "$(./sum 5 10)" != "15" ]
            then
                exit 1
            fi

            if [ "$(./sum 10 20)" != "30" ]
            then
                exit 1
            fi

            if [ "$(./sum string not_supported)" != "0" ]
            then
                exit 1
            fi

            if [ "$(./sum 2147483647 0)" != "2147483647" ]
            then
                exit 1
            fi
                  