name: tester

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v2
      - name: Tester name
        run: echo "Tested by Bogdan"
      - name: Compile
        run: gcc ../../sum.c -o ../../sum