name: tester

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - run: echo "Tested by Bogdan"
      - run: gcc sum.c -o sum; ./sum 1 2