name: tester

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - name: Tester name
      - run: echo "Tested by Bogdan"
      - name: Compile
      - run: gcc ../../sum.c -o ../../sum