name: tester

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v2
      - name: Tester name
        run: echo "Tested by Bogdan"
      - name: Get working directory
        run: pwd
      - name: Compile
        run: gcc -o sum sum.c
      - name: Test1 (should be 15)
        run: ./sum 5 10
      - name: Test2 (should be 2147483647)
        run: ./sum 2147483647 0
      - name: Test3 (should be -2147483647)
        run: ./sum 0 -2147483647
      - name: Test4 (should exceed upper int bounds)
        run: ./sum 21474836471 1
      - name: Test5 (should exceed lower int bounds)
        run: ./sum -21347483647 -1
      - name: Test6 (should return an error)
        run: ./sum wrong input