name: tester

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v2
      - name: Tester name
        run: echo "Tested by Bogdan"
      - name: Get working directory
        run: pwd
      - name: Compile
        run: gcc -o sum sum.c
      - name: Test cases
        run: |
            chmod a+x testcases.sh
            ./testcases.sh
                  